WINDOW_TITLE = 'Quadtree'
WINDOW_SIZE = (750,750)

# Centered in window
BORDER_WIDTH = 25
# left, right, top, bottom
QT_SIDES = (BORDER_WIDTH, WINDOW_SIZE[0]-BORDER_WIDTH,
			BORDER_WIDTH, WINDOW_SIZE[1]-BORDER_WIDTH)

GREEN = (0,255,0)
BLACK = (0,0,0)
WHITE = (255,255,255)
